[package]
name = "rv"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/songww/relmvim"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
which = "4"
anyhow = "1"
fragile = "1"
futures = "0.3"
tracker = "0.1"
once_cell = "1"
derivative = "2"
derive-new = "0.5"
env_logger = "0.9"
rustc-hash = "1"
vector-map = "1"
async-trait = "0.1"
derive_more = "0.99"
pin-project = "1"
clap = { version = "3", features = [ "derive" ] }
chan = { version = "0.5", package = "crossbeam-channel" }
nvim = { version = "0.4", package = "nvim-rs", features = [ "use_tokio" ] }

pangocairo = "0.15"
graphene-rs = "0.15"
glib = { version = "0.15", features = [ "v2_70" ] }
pango = { version = "0.15", features = [ "v1_50" ] }
gdk = { version = "0.4", package = "gdk4", features = [ "v4_6" ] }
gtk = { version = "0.4", package = "gtk4", features = [ "v4_6" ] }
cairo = { version = "0.15", package = "cairo-rs", features = [ "v1_16", "png" ] }
adw = { version = "0", package = "libadwaita" }

relm4 = {  version = "0.4", features = [ "tokio-rt", "libadwaita" ] }
relm-macros = { version = "0.4", package = "relm4-macros" }
relm-components = { version = "0.4", package = "relm4-components" }

tokio = { version = "1", features = ["process", "io-util", "sync", "rt", "time", "signal", "rt-multi-thread"] }
tokio-util = { version = "0.7", features = ["compat"] }

[profile.release]
debug = true

[patch.tuna]
"pango" = { path = '/home/songww/workspace/github.com/gtk-rs-core/pango' }
[patch.crates-io]
"pango" = { path = '/home/songww/workspace/github.com/gtk-rs-core/pango' }

[workspace]
members = [
    "textview"
]
