[package]
name = "rv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
which = "4"
anyhow = "1"
fragile = "1"
futures = "0.3"
once_cell = "1"
derive-new = "0.5"
env_logger = "0.9"
rustc-hash = "1"
async-trait = "0.1"
derive_more = "0.99"
pin-project = "1"
clap = { version = "3", features = [ "derive" ] }
chan = { version = "0.5", package = "crossbeam-channel" }
nvim = { version = "0.4", package = "nvim-rs", features = [ "use_tokio" ] }

glib = "0.15"
pango = "0.15"
pangocairo = "0.15"
graphene-rs = "0.15"
cairo = { version = "0.15", package = "cairo-rs" }
gdk = { version = "0.4", package = "gdk4", features = [ "v4_4" ] }
gtk = { version = "0.4", package = "gtk4", features = [ "v4_4" ] }

relm4 = { version = "0.4", features = ["tokio-rt"] }
relm-macros = { version = "0.4", package = "relm4-macros" }
relm-components = { version = "0.4", package = "relm4-components" }

tokio = { version = "1", features = ["process", "io-util", "sync", "rt", "time", "signal", "rt-multi-thread"] }
tokio-util = { version = "0.6", features = ["compat"] }
